services:
  postgres:
    image: postgres:17
    restart: always
    container_name: postgres_db
    healthcheck: 
      test: [ "CMD-SHELL", "pg_isready -U  ${POSTGRES_USER} -d ${NAME_DB}" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${NAME_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: shopnavi_bot
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

    environment:
      TOKEN: ${TOKEN}
      POSTGRES_CONFIG: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${HOST}:${PORT}/${NAME_DB}
      PAY_API_KEY: ${PAY_API_KEY}
      SHOP_ID: ${SHOP_ID}
      SECRET_KEY: ${SECRET_KEY}
      


    volumes:
      - .:/app

volumes:
  postgres_data:
