services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data


  bot:
    build:
      context: . 
      dockerfile: Dockerfile

    container_name: shopnavi_bot
    depends_on:
      - postgres

    dumps:
      - ./data:/data
    environment:
      TOKEN: ${TOKEN}
      POSTGRES_CONFIG: ${POSTGRES_CONFIG}
      PAY_API_KEY:  ${PAY_API_KEY}
      SHOP_ID:  ${SHOP_ID}
      SECRET_KEY:  ${SECRET_KEY}

    volumes:
      - .:/app

volumes:
  postgres_data:

    